apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: niun02yp9-python 
  janus-idp.io/tekton: niun02yp9-python
  backstage.io/kubernetes-id: niun02yp9-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: niun02yp9-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml