apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: niun02yp9-python
  janus-idp.io/tekton: niun02yp9-python
  backstage.io/kubernetes-id: niun02yp9-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: niun02yp9-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
